Repository lo1tuma/eslint-plugin-mocha, pull requests merged in 2018-03, with the labels that each got.

#149 Fix complexity problems
  lib/rules/handle-done-callback.js
  lib/rules/no-global-tests.js
  lib/rules/no-mocha-arrows.js
  lib/rules/no-nested-tests.js
  lib/rules/no-pending-tests.js
  lib/rules/no-return-and-callback.js
  lib/rules/no-sibling-hooks.js
  lib/rules/no-skipped-tests.js
  lib/rules/valid-suite-description.js
  lib/rules/valid-test-description.js
  lib/util/ast.js
  test/rules/no-mocha-arrows.js
Labels: bug

#150 chore(package): update mocha to version 5.0.1
  package.json
Labels: upgrade

#147 Adds rule "no setup in describe"
  docs/rules/README.md
  docs/rules/no-setup-in-describe.md
  index.js
  lib/rules/no-setup-in-describe.js
  test/rules/no-setup-in-describe.js
Labels: feature

#154 Remove support for nodejs 4, 5 and 7
  .travis.yml
Labels: breaking

#155 Remove support for ESLint versions < 4.0.0
  README.md
  package.json
Labels: breaking

#152 Whitelist files instead of using .npmignore
  .npmignore
  package.json
Labels: build

#153 Use nyc instead of istanbul
  .gitignore
  .istanbul.yml
  package.json
Labels: build

#151 Update chai to version 4.1.2
  package.json
  test/index.js
Labels: upgrade

#156 Use new language features
  .eslintrc
  .eslintrc.json
  lib/rules/handle-done-callback.js
  lib/rules/max-top-level-suites.js
  lib/rules/no-exclusive-tests.js
  lib/rules/no-global-tests.js
  lib/rules/no-hooks-for-single-case.js
  lib/rules/no-hooks.js
  lib/rules/no-identical-title.js
  lib/rules/no-mocha-arrows.js
  lib/rules/no-nested-tests.js
  lib/rules/no-pending-tests.js
  lib/rules/no-return-and-callback.js
  lib/rules/no-setup-in-describe.js
  lib/rules/no-sibling-hooks.js
  lib/rules/no-skipped-tests.js
  lib/rules/no-synchronous-tests.js
  lib/rules/no-top-level-hooks.js
  lib/rules/valid-suite-description.js
  lib/rules/valid-test-description.js
  lib/util/ast.js
  lib/util/settings.js
  package.json
  test/.eslintrc
  test/index.js
  test/rules/handle-done-callback.js
  test/rules/max-top-level-suites.js
  test/rules/no-exclusive-tests.js
  test/rules/no-global-tests.js
  test/rules/no-hooks-for-single-case.js
  test/rules/no-hooks.js
  test/rules/no-identical-title.js
  test/rules/no-mocha-arrows.js
  test/rules/no-nested-tests.js
  test/rules/no-pending-tests.js
  test/rules/no-return-and-callback.js
  test/rules/no-setup-in-describe.js
  test/rules/no-sibling-hooks.js
  test/rules/no-skipped-tests.js
  test/rules/no-synchronous-tests.js
  test/rules/no-top-level-hooks.js
  test/rules/valid-suite-description.js
  test/rules/valid-test-description.js
Labels: refactor
