Repository lo1tuma/eslint-plugin-mocha, pull requests merged in 2018-07, with the labels that each got.

#167 Issue #166: No setup in describe hooks
  lib/rules/no-setup-in-describe.js
  test/rules/no-setup-in-describe.js
Labels: bug

#163 Adds mocha-aware prefer-arrow-callback rule
  docs/rules/README.md
  docs/rules/prefer-arrow-callback.md
  index.js
  lib/rules/prefer-arrow-callback.js
  test/rules/prefer-arrow-callback.js
Labels: feature

#168 Update nyc to version 12.0.2
  package.json
Labels: upgrade

#169 Update eslint to version 5.0.1
  package.json
Labels: upgrade

#171 Add node 10 build environment
  .travis.yml
Labels: build
