Repository lo1tuma/eslint-plugin-mocha, pull requests merged in 2019-11, with the labels that each got.

#220 Support TDD interface in no-setup-in-describe
  lib/util/ast.js
  test/rules/no-setup-in-describe.js
Labels: bug

#222 ✉️ Send a webhook to Coveralls when the build completes
  .github/workflows/ci.yml
Labels: build

#223 ♻️ Replace Travis build badge with GitHub Actions badge
  README.md
Labels: documentation
