Repository lo1tuma/eslint-plugin-mocha, pull requests merged in 2019-01, with the labels that each got.

#186 Remove invalid test-cases and unreachable code from prefer-arrow-callback
  lib/rules/prefer-arrow-callback.js
  test/rules/prefer-arrow-callback.js
Labels: bug

#184 Fixing typo
  docs/rules/README.md
Labels: documentation

#187 Update dependencies
  package.json
Labels: upgrade
