Repository lo1tuma/eslint-plugin-mocha, pull requests merged in 2020-07, with the labels that each got.

#258 remove autofix from no-skipped-tests rule fix
  docs/rules/README.md
  docs/rules/no-skipped-tests.md
  lib/rules/no-skipped-tests.js
  test/rules/no-skipped-tests.js
Labels: breaking

#259 Update dependencies
  package-lock.json
  package.json
Labels: upgrade

#260 New option `ignoreSkipped` for `handle-done-callback` rule
  .eslintrc.json
  docs/rules/handle-done-callback.md
  lib/rules/handle-done-callback.js
  lib/util/ast.js
  lib/util/names.js
  test/rules/handle-done-callback.js
  test/util/namesSpec.js
Labels: enhancement

#261 Use includes instead of indexOf
  .eslintrc.json
  lib/rules/no-exclusive-tests.js
  lib/rules/no-hooks-for-single-case.js
  lib/rules/no-identical-title.js
  lib/rules/no-setup-in-describe.js
  lib/rules/no-skipped-tests.js
  lib/rules/valid-suite-description.js
  lib/rules/valid-test-description.js
  lib/util/ast.js
  package-lock.json
  package.json
Labels: refactor
