Repository lo1tuma/eslint-plugin-mocha, pull requests merged in 2020-02, with the labels that each got.

#227 Alphabetize rule lists
  index.js
Labels: refactor

#226 add plugin to recommended config
  index.js
Labels: enhancement

#228 Add `fixable` property to fixable rules (and mention in docs)
  docs/rules/README.md
  docs/rules/no-async-describe.md
  docs/rules/no-mocha-arrows.md
  docs/rules/prefer-arrow-callback.md
  lib/rules/no-async-describe.js
  lib/rules/no-mocha-arrows.js
  lib/rules/no-skipped-tests.js
Labels: enhancement

#230 - npm: Add package-lock.json
  package-lock.json
Labels: build

#231 Doc syntax issue
  docs/rules/no-synchronous-tests.md
Labels: documentation

#232 Add `u` flag in RegExp for `valid-test-description` and `valid-suite-description`
  lib/rules/valid-suite-description.js
  lib/rules/valid-test-description.js
Labels: enhancement

#233 "Options" heading in doc files (and consistent level 2 heading)
  docs/rules/max-top-level-suites.md
  docs/rules/no-exclusive-tests.md
  docs/rules/no-hooks-for-single-case.md
  docs/rules/no-skipped-tests.md
  docs/rules/no-synchronous-tests.md
  docs/rules/valid-suite-description.md
  docs/rules/valid-test-description.md
Labels: documentation

#229 Indicate whether rule is recommended
  docs/rules/README.md
  test/index.js
Labels: documentation

#234 Add schemas for options (and remove for files which are using settings)
  lib/rules/max-top-level-suites.js
  lib/rules/no-exclusive-tests.js
  lib/rules/no-hooks-for-single-case.js
  lib/rules/no-skipped-tests.js
  lib/rules/no-synchronous-tests.js
  lib/rules/valid-suite-description.js
  lib/rules/valid-test-description.js
  test/rules/valid-suite-description.js
  test/rules/valid-test-description.js
Labels: enhancement

#235 Nondeprecated rule format
  lib/rules/handle-done-callback.js
  lib/rules/no-global-tests.js
  lib/rules/no-hooks.js
  lib/rules/no-identical-title.js
  lib/rules/no-nested-tests.js
  lib/rules/no-pending-tests.js
  lib/rules/no-return-and-callback.js
  lib/rules/no-return-from-async.js
  lib/rules/no-setup-in-describe.js
  lib/rules/no-sibling-hooks.js
  lib/rules/no-top-level-hooks.js
Labels: refactor

#236 no-hooks: add option to allow certain kind of hooks
  docs/rules/no-hooks.md
  lib/rules/no-hooks.js
  test/rules/no-hooks.js
Labels: enhancement

#239 Fix max-top-level-suites to ignore generated suites
  lib/rules/max-top-level-suites.js
  test/rules/max-top-level-suites.js
Labels: bug

#238 no-hooks-for-single-case: fix false postive in nested suites
  lib/rules/no-hooks-for-single-case.js
  test/rules/no-hooks-for-single-case.js
Labels: bug
