Repository lo1tuma/eslint-plugin-mocha, pull requests merged in 2021-12, with the labels that each got.

#305 Remove unavailable badge from README
  README.md
Labels: documentation

#307 Turn off no-hooks-for-single-case in recommended
  docs/rules/README.md
  index.js
Labels: breaking

#309 chore: switch yarn command to npm
  .github/workflows/ci.yml
Labels: refactor

#315 Fix no-empty-description rule to not report on dynamic values
  lib/rules/no-empty-description.js
  test/rules/no-empty-description.js
Labels: bug
