Repository lo1tuma/eslint-plugin-mocha, pull requests merged in 2023-09, with the labels that each got.

#336 Support function calls as custom names (to stop false warnings)
  README.md
  lib/util/ast.js
  test/rules/max-top-level-suites.js
  test/rules/no-async-describe.js
  test/rules/no-exclusive-tests.js
  test/rules/no-sibling-hooks.js
  test/rules/no-skipped-tests.js
  test/rules/no-top-level-hooks.js
Labels: feature

#338 Include Node.js v20 in continuous integration pipeline
  .github/workflows/ci.yml
Labels: build

#339 Add screendriver to contributors
  package.json
Labels: documentation
